language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: pX3bLZKUnA5wKUk7sgNvOAwekZeTtT8VhtJ8XzESoWLC3nN4eyXMg0z3LwJd2SrmDwy73phYg6lx0UOYWmDuNP/JUdnMsFZNuaUbYYhQ4df7kMDvmxV2eFfakliSKjgINPuwr+flMFMp3UgzHwiGZWt2y0M5FijJNlhClsAGBid7hGZ+j9Yo9qPMDtakwLWDu/iZ3AsvF3SXhZTiRrmJr8GW3op040uBa8CwzwTWZ3e+rUw9s/BjA32GxG9voUqxoprPUvIr6qXf+0gPMBP+OluhuECUFMWt1ExcHDaUySypp1jP+2R91SQrHlosxKGhiqmokp4myVbbdJVMtuYEJq2QeCy++2wq0+d50K+QXt/epx0Xxk2iUcrDe7QWDS3qawowICOSkOuq014JBmuiSNeiFNfd28mimB6PTVPxQ0KmEhhnz4PpMI9FsfaVzgfY+VVJ1LOydZKVV6FI0H5w/Rx52bec2dByb8YGQFyaQTIuYRSptL9mA2hP8LpDSzywrEYafbRxDYwbspxh/LvcERl/J6rTHpBqE839PHiisTZaXP9u+tq5Mgz3TZhlVKPMqWIOmtmxO/3U2w7y37AqiD3ZthamrTaMLvFrXzYj1CpzH5C770V1J/uLFc0T8O5cEUwuy/QX5gPOwjKJ91cGNBDOnDz8blbq/l85atqrWzQ=
  app: https://infinite-woodland-61685.herokuapp.com/
  on:
    repo: EnshaednHiker/node-shopping-list-integration-tests
